# Generated by Django 4.2.4 on 2023-08-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('published_at', models.DateTimeField(help_text='発売日', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
