# Generated by Django 4.2.4 on 2023-08-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookstore", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.UUIDField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
